print("my name is Kelsey")
print("I am 17 years old") 
print("I come from Nairobi county")
print("I love art,music and poetry")
print("------------------")
print("******************")
print("##################")